### ISSUE TITLE
[Evolution][Search][AjaxSearch] Mobile search dropdown hiding when pressing Done

### ISSUE THREAD

**Issue by websuits** [breezefront/theme-frontend-breeze-evolution#5]
1. I'm on mobile
2. I click on search icon
3. The search field appears
4. I type something in the field
5. I press Done after typing so i can scroll in the results
6. Dropdown is hiding

Expectation: Dropdown to keep showing until i click/touch outside
Possible solution : add an X icon in the right side on the search field that will close the search

![IMG_1184](https://user-images.githubusercontent.com/42982977/189548408-d5a4d644-45d8-4912-b85f-aaaec7ef0f75.jpg)

![IMG_1185](https://user-images.githubusercontent.com/42982977/189548422-270d41b7-6332-411d-955f-83e9ce0b3dc7.jpg)

**Comment by vovayatsyuk** [comment]
I don't like the idea to keep it visible on "Done". Some users may use "Done" to hide the popup and expect this behavior.

As a workaround, you can add a "title" above the results. Clicking on that title will not trigger a page reload but the keyboard will hide.

```less
& when not (@critical) {
    #search_autocomplete::before {
        display: block;
        content: 'Results';
        font-size: .9rem;
        font-weight: 500;
        text-transform: uppercase;
        color: @muted__color;
        .lib-css(padding, @dropdown-item__padding);
    }
}
```

<img src="https://user-images.githubusercontent.com/306080/190193125-8f256408-a234-4ece-9e79-dab2b3aaf6e0.jpeg" width="300"/>
